### ISSUE TITLE
Exception when trying to plot histogram of temperature in current scenario

### ISSUE THREAD

**Issue by Sciss** [iem-projects/sysson#22]
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: Must be finite.
    at org.jfree.chart.axis.NumberTickUnitSource.getCeilingTickUnit(NumberTickUnitSource.java:114)
    at org.jfree.chart.axis.NumberAxis.selectHorizontalAutoTickUnit(NumberAxis.java:855)
    at org.jfree.chart.axis.NumberAxis.selectAutoTickUnit(NumberAxis.java:824)
    at org.jfree.chart.axis.NumberAxis.refreshTicksHorizontal(NumberAxis.java:949)
    at org.jfree.chart.axis.NumberAxis.refreshTicks(NumberAxis.java:921)
    at org.jfree.chart.axis.ValueAxis.reserveSpace(ValueAxis.java:822)
    at org.jfree.chart.plot.XYPlot.calculateDomainAxisSpace(XYPlot.java:3031)
    at org.jfree.chart.plot.XYPlot.calculateAxisSpace(XYPlot.java:2990)
    at org.jfree.chart.plot.XYPlot.draw(XYPlot.java:3132)
    at org.jfree.chart.JFreeChart.draw(JFreeChart.java:1229)
    at org.jfree.chart.ChartPanel.paintComponent(ChartPanel.java:1628)
```

**Comment by Sciss** [comment]
There is no good way to fix this, as the data set had bad bounds (excessive ta values not corresponding to fill values); we now catch the exception and draw an error string.
